services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2101Dsalas
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: 2101Dsalas
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: